"""Test suite for the create-a-time-slider example."""

from __future__ import annotations

from maplibreum import Map


# Sample of the earthquake dataset with month property applied in the
# original gallery example. The features below keep the structure but
# drastically reduce the payload so the regression test remains light.
_EARTHQUAKE_DATA = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [142.369, 38.322]},
            "properties": {"mag": 7.0, "time": 1425640986000, "month": 2},
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [94.195, 26.692]},
            "properties": {"mag": 6.5, "time": 1429712490000, "month": 3},
        },
        {
            "type": "Feature",
            "geometry": {"type": "Point", "coordinates": [-71.674, -31.573]},
            "properties": {"mag": 6.9, "time": 1438211046000, "month": 6},
        },
    ],
}


_CIRCLE_LAYER = {
    "id": "earthquake-circles",
    "type": "circle",
    "source": "earthquakes",
    "paint": {
        "circle-color": [
            "interpolate",
            ["linear"],
            ["get", "mag"],
            6,
            "#FCA107",
            8,
            "#7F3121",
        ],
        "circle-opacity": 0.75,
        "circle-radius": [
            "interpolate",
            ["linear"],
            ["get", "mag"],
            6,
            20,
            8,
            40,
        ],
    },
}


_LABEL_LAYER = {
    "id": "earthquake-labels",
    "type": "symbol",
    "source": "earthquakes",
    "layout": {
        "text-field": ["concat", ["to-string", ["get", "mag"]], "m"],
        "text-font": ["Noto Sans Regular"],
        "text-size": 12,
    },
    "paint": {"text-color": "rgba(0,0,0,0.5)"},
}


def test_create_a_time_slider() -> None:
    """Test time slider using improved Python API (Phase 2 improvement).

    This version eliminates JavaScript injection by:
    1. Using SliderControl class instead of manual DOM manipulation
    2. Providing a clean Python API for temporal filtering
    3. Auto-generating JavaScript and CSS from Python configuration
    """
    from maplibreum.controls import SliderControl

    months = [
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    ]

    m = Map(
        map_style="https://demotiles.maplibre.org/style.json",
        center=[31.4606, 20.7927],
        zoom=0.5,
    )

    m.add_source("earthquakes", _EARTHQUAKE_DATA)
    m.add_layer(_CIRCLE_LAYER)
    m.add_layer(_LABEL_LAYER)

    # Create slider control with Python API
    slider = SliderControl(
        layer_ids=["earthquake-circles", "earthquake-labels"],
        property_name="month",
        min_value=0,
        max_value=11,
        step=1,
        initial_value=0,
        value_labels=months,
        title="Significant earthquakes in 2015",
        show_legend=True,
        legend_gradient="linear-gradient(to right, #fca107, #7f3121)",
        legend_label="Magnitude (m)",
    )

    # Add slider CSS and JavaScript
    m.custom_css = slider.to_css()
    m.add_on_load_js(slider.to_js())

    html = m.render()

    # Verify Python API usage
    assert '"center": [31.4606, 20.7927]' in html
    assert '"zoom": 0.5' in html
    assert 'map.addSource("earthquakes"' in html

    # Verify SliderControl is present
    assert "maplibreum-slider" in html
    assert "Significant earthquakes in 2015" in html
    assert "Magnitude (m)" in html

    # Verify slider functionality
    assert 'type="range"' in html
    assert "applyFilter" in html
    assert "map.setFilter" in html
    assert "addEventListener('input'" in html

    # Verify month labels
    assert "January" in html
    assert "December" in html

    # Verify no manual DOM manipulation
    assert "slider.addEventListener('input'" in html  # Generated by SliderControl

    # Verify legend gradient
    assert "linear-gradient(to right, #fca107, #7f3121)" in html
