name: Deploy Examples to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/setup.cfg
            
      - name: Install dependencies
        run: |
          pip install -e .
          pip install jupyter nbconvert
          
      - name: Create output directory
        run: |
          mkdir -p docs
          
      - name: Execute and convert notebooks to HTML
        run: |
          cd examples
          for notebook in *.ipynb; do
            echo "Processing $notebook..."
            if jupyter nbconvert --to html --execute "$notebook" --output-dir ../docs/ --allow-errors --ExecutePreprocessor.timeout=300; then
              echo "Successfully executed and converted $notebook"
            else
              echo "Warning: Failed to execute $notebook, converting without execution"
              jupyter nbconvert --to html "$notebook" --output-dir ../docs/
            fi
          done
          
      - name: Create index page
        run: |
          cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>MapLibreum Examples</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      line-height: 1.6;
                      color: #333;
                  }
                  h1 {
                      color: #2c3e50;
                      border-bottom: 2px solid #3498db;
                      padding-bottom: 10px;
                  }
                  .example-list {
                      list-style: none;
                      padding: 0;
                  }
                  .example-item {
                      background: #f8f9fa;
                      margin: 10px 0;
                      padding: 15px;
                      border-radius: 8px;
                      border-left: 4px solid #3498db;
                  }
                  .example-item a {
                      text-decoration: none;
                      color: #2c3e50;
                      font-weight: 500;
                  }
                  .example-item a:hover {
                      color: #3498db;
                  }
                  .description {
                      color: #666;
                      font-size: 0.9em;
                      margin-top: 5px;
                  }
                  .footer {
                      margin-top: 40px;
                      padding-top: 20px;
                      border-top: 1px solid #eee;
                      text-align: center;
                      color: #666;
                  }
              </style>
          </head>
          <body>
              <h1>MapLibreum Examples Gallery</h1>
              <p>Interactive MapLibre maps created with MapLibreum - a Python library for building beautiful, interactive maps.</p>
              
              <ul class="example-list">
                  <li class="example-item">
                      <a href="creative_maplibreum_examples.html">Creative MapLibreum Examples & Tutorials</a>
                      <div class="description">Comprehensive collection of creative examples showcasing MapLibreum's features including markers, styling, and interactive elements.</div>
                  </li>
                  <li class="example-item">
                      <a href="usage.html">Basic Usage Examples</a>
                      <div class="description">Fundamental usage patterns for creating maps with controls, GeoJSON layers, and popups.</div>
                  </li>
                  <li class="example-item">
                      <a href="new_features.html">New Features Demo</a>
                      <div class="description">Demonstration of the latest MapLibreum features including sources, layers, and advanced controls.</div>
                  </li>
                  <li class="example-item">
                      <a href="event_handling.html">Event Handling</a>
                      <div class="description">Interactive examples showing how to handle map events like clicks and movements with callback functions.</div>
                  </li>
              </ul>
              
              <div class="footer">
                  <p>Built with ❤️ using <a href="https://github.com/kauevestena/maplibreum_prototype">MapLibreum</a></p>
                  <p>Generated from Jupyter notebooks</p>
              </div>
          </body>
          </html>
          EOF
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4